### ISSUE TITLE
Congelamento

### ISSUE THREAD

**Issue by rpotalara** [TBertuzzi/Consulta.CNPJ#1]
@TBertuzzi , encontrei essa rotina desenvolvida por você e resolvi testar e não obtive sucesso. Como já faz algum tempo que ela foi atualizada pela última vez você poderia informar se ela ainda funciona? Fiz um teste direto na API https://www.receitaws.com.br/v1/cnpj/1234567890134 e ela responde normalmente.
Debuguei e esta congelando em:
using (HttpResponseMessage response = await _httpClient.GetAsync(string.Format(Constantes.CNPJAPI, cnpj))) do CNPJService.cs

Obrigado.

**Comment by TBertuzzi** [comment]
Desculpe a demora, mas o github não me notificou dessa issue. Vou verificar. Obrigado

**Comment by TBertuzzi** [comment]
Corrigido e atualizado pacote nuget. Obrigado

**Comment by rpotalara** [comment]
> Corrigido e atualizado pacote nuget. Obrigado

Obrigado.
